// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomService.Data;

#nullable disable

namespace RoomService.Migrations
{
    [DbContext(typeof(RoomDbContext))]
    partial class RoomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoomService.Models.Amenity", b =>
                {
                    b.Property<int>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AmenityId");

                    b.ToTable("MyRoomAmenitiesMaster");

                    b.HasData(
                        new
                        {
                            AmenityId = 1,
                            Category = "Climate",
                            Description = "Climate controlled room temperature",
                            Icon = "ac_unit",
                            IsActive = true,
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            AmenityId = 2,
                            Category = "Climate",
                            Description = "Central heating system",
                            Icon = "thermostat",
                            IsActive = true,
                            Name = "Heating"
                        },
                        new
                        {
                            AmenityId = 3,
                            Category = "Food & Drink",
                            Description = "In-room mini refrigerator with beverages",
                            Icon = "local_bar",
                            IsActive = true,
                            Name = "Mini Bar"
                        },
                        new
                        {
                            AmenityId = 4,
                            Category = "Food & Drink",
                            Description = "In-room coffee and tea maker",
                            Icon = "coffee_maker",
                            IsActive = true,
                            Name = "Coffee Maker"
                        },
                        new
                        {
                            AmenityId = 5,
                            Category = "Food & Drink",
                            Description = "24-hour room service available",
                            Icon = "room_service",
                            IsActive = true,
                            Name = "Room Service"
                        },
                        new
                        {
                            AmenityId = 6,
                            Category = "Entertainment",
                            Description = "LED/LCD flat screen television",
                            Icon = "tv",
                            IsActive = true,
                            Name = "Flat Screen TV"
                        },
                        new
                        {
                            AmenityId = 7,
                            Category = "Entertainment",
                            Description = "Premium cable channels",
                            Icon = "live_tv",
                            IsActive = true,
                            Name = "Cable/Satellite TV"
                        },
                        new
                        {
                            AmenityId = 8,
                            Category = "Technology",
                            Description = "High-speed wireless internet",
                            Icon = "wifi",
                            IsActive = true,
                            Name = "Free WiFi"
                        },
                        new
                        {
                            AmenityId = 9,
                            Category = "Business",
                            Description = "Dedicated workspace with chair",
                            Icon = "desk",
                            IsActive = true,
                            Name = "Work Desk"
                        },
                        new
                        {
                            AmenityId = 10,
                            Category = "Security",
                            Description = "In-room electronic safe",
                            Icon = "lock",
                            IsActive = true,
                            Name = "Safe Box"
                        },
                        new
                        {
                            AmenityId = 11,
                            Category = "Bathroom",
                            Description = "Private bathtub",
                            Icon = "bathtub",
                            IsActive = true,
                            Name = "Bathtub"
                        },
                        new
                        {
                            AmenityId = 12,
                            Category = "Bathroom",
                            Description = "Rainfall showerhead",
                            Icon = "shower",
                            IsActive = true,
                            Name = "Rain Shower"
                        },
                        new
                        {
                            AmenityId = 13,
                            Category = "Bathroom",
                            Description = "In-room hair dryer",
                            Icon = "dry",
                            IsActive = true,
                            Name = "Hair Dryer"
                        },
                        new
                        {
                            AmenityId = 14,
                            Category = "Bathroom",
                            Description = "Complimentary bathroom amenities",
                            Icon = "soap",
                            IsActive = true,
                            Name = "Toiletries"
                        },
                        new
                        {
                            AmenityId = 15,
                            Category = "Outdoor",
                            Description = "Private balcony or terrace",
                            Icon = "balcony",
                            IsActive = true,
                            Name = "Balcony"
                        },
                        new
                        {
                            AmenityId = 16,
                            Category = "View",
                            Description = "Room with ocean/sea view",
                            Icon = "waves",
                            IsActive = true,
                            Name = "Sea View"
                        },
                        new
                        {
                            AmenityId = 17,
                            Category = "View",
                            Description = "Room with city skyline view",
                            Icon = "location_city",
                            IsActive = true,
                            Name = "City View"
                        },
                        new
                        {
                            AmenityId = 18,
                            Category = "Bedding",
                            Description = "Large king size bed",
                            Icon = "king_bed",
                            IsActive = true,
                            Name = "King Size Bed"
                        },
                        new
                        {
                            AmenityId = 19,
                            Category = "Comfort",
                            Description = "Light-blocking window curtains",
                            Icon = "curtains",
                            IsActive = true,
                            Name = "Blackout Curtains"
                        },
                        new
                        {
                            AmenityId = 20,
                            Category = "Convenience",
                            Description = "Iron and ironing board",
                            Icon = "iron",
                            IsActive = true,
                            Name = "Iron & Board"
                        });
                });

            modelBuilder.Entity("RoomService.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("BedCount")
                        .HasColumnType("int");

                    b.Property<string>("BedType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("RoomSize")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RoomId");

                    b.HasIndex("HotelId");

                    b.HasIndex("HotelId", "RoomNumber")
                        .IsUnique();

                    b.ToTable("MyRooms");
                });

            modelBuilder.Entity("RoomService.Models.RoomAmenity", b =>
                {
                    b.Property<int>("RoomAmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomAmenityId"));

                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("RoomAmenityId");

                    b.HasIndex("AmenityId");

                    b.HasIndex("RoomId", "AmenityId")
                        .IsUnique();

                    b.ToTable("MyRoomAmenities");
                });

            modelBuilder.Entity("RoomService.Models.RoomAmenity", b =>
                {
                    b.HasOne("RoomService.Models.Amenity", "Amenity")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoomService.Models.Room", "Room")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RoomService.Models.Amenity", b =>
                {
                    b.Navigation("RoomAmenities");
                });

            modelBuilder.Entity("RoomService.Models.Room", b =>
                {
                    b.Navigation("RoomAmenities");
                });
#pragma warning restore 612, 618
        }
    }
}
