// <auto-generated />
using System;
using HotelService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelService.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelService.Models.Amenity", b =>
                {
                    b.Property<int>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AmenityId");

                    b.ToTable("MyAmenities");

                    b.HasData(
                        new
                        {
                            AmenityId = 1,
                            Category = "Internet",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 10, 52, 722, DateTimeKind.Utc).AddTicks(2572),
                            Description = "High-speed wireless internet",
                            Icon = "wifi",
                            IsActive = true,
                            Name = "Free WiFi"
                        },
                        new
                        {
                            AmenityId = 2,
                            Category = "Recreation",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 10, 52, 722, DateTimeKind.Utc).AddTicks(2585),
                            Description = "Outdoor swimming pool",
                            Icon = "pool",
                            IsActive = true,
                            Name = "Swimming Pool"
                        },
                        new
                        {
                            AmenityId = 3,
                            Category = "Recreation",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 10, 52, 722, DateTimeKind.Utc).AddTicks(2588),
                            Description = "Fully equipped fitness center",
                            Icon = "fitness_center",
                            IsActive = true,
                            Name = "Gym"
                        },
                        new
                        {
                            AmenityId = 4,
                            Category = "Wellness",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 10, 52, 722, DateTimeKind.Utc).AddTicks(2592),
                            Description = "Full-service spa and wellness center",
                            Icon = "spa",
                            IsActive = true,
                            Name = "Spa"
                        },
                        new
                        {
                            AmenityId = 5,
                            Category = "Dining",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 10, 52, 722, DateTimeKind.Utc).AddTicks(2593),
                            Description = "On-site dining restaurant",
                            Icon = "restaurant",
                            IsActive = true,
                            Name = "Restaurant"
                        },
                        new
                        {
                            AmenityId = 6,
                            Category = "Dining",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 10, 52, 722, DateTimeKind.Utc).AddTicks(2595),
                            Description = "Lounge bar with beverages",
                            Icon = "local_bar",
                            IsActive = true,
                            Name = "Bar"
                        },
                        new
                        {
                            AmenityId = 7,
                            Category = "Services",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 10, 52, 722, DateTimeKind.Utc).AddTicks(2597),
                            Description = "Free parking available",
                            Icon = "local_parking",
                            IsActive = true,
                            Name = "Parking"
                        },
                        new
                        {
                            AmenityId = 8,
                            Category = "Services",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 10, 52, 722, DateTimeKind.Utc).AddTicks(2599),
                            Description = "24-hour room service",
                            Icon = "room_service",
                            IsActive = true,
                            Name = "Room Service"
                        },
                        new
                        {
                            AmenityId = 9,
                            Category = "Services",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 10, 52, 722, DateTimeKind.Utc).AddTicks(2601),
                            Description = "Laundry and dry cleaning services",
                            Icon = "local_laundry_service",
                            IsActive = true,
                            Name = "Laundry"
                        },
                        new
                        {
                            AmenityId = 10,
                            Category = "Transport",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 10, 52, 722, DateTimeKind.Utc).AddTicks(2602),
                            Description = "Airport pickup and drop service",
                            Icon = "airport_shuttle",
                            IsActive = true,
                            Name = "Airport Shuttle"
                        },
                        new
                        {
                            AmenityId = 11,
                            Category = "Business",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 10, 52, 722, DateTimeKind.Utc).AddTicks(2604),
                            Description = "Business center with meeting rooms",
                            Icon = "business_center",
                            IsActive = true,
                            Name = "Business Center"
                        },
                        new
                        {
                            AmenityId = 12,
                            Category = "Business",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 10, 52, 722, DateTimeKind.Utc).AddTicks(2606),
                            Description = "Conference and event facilities",
                            Icon = "meeting_room",
                            IsActive = true,
                            Name = "Conference Room"
                        },
                        new
                        {
                            AmenityId = 13,
                            Category = "Services",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 10, 52, 722, DateTimeKind.Utc).AddTicks(2607),
                            Description = "Pets are allowed",
                            Icon = "pets",
                            IsActive = true,
                            Name = "Pet Friendly"
                        },
                        new
                        {
                            AmenityId = 14,
                            Category = "Room",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 10, 52, 722, DateTimeKind.Utc).AddTicks(2609),
                            Description = "Climate controlled rooms",
                            Icon = "ac_unit",
                            IsActive = true,
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            AmenityId = 15,
                            Category = "Services",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 10, 52, 722, DateTimeKind.Utc).AddTicks(2611),
                            Description = "Round the clock reception",
                            Icon = "support_agent",
                            IsActive = true,
                            Name = "24/7 Front Desk"
                        });
                });

            modelBuilder.Entity("HotelService.Models.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("HotelId");

                    b.HasIndex("City");

                    b.HasIndex("Name");

                    b.ToTable("MyHotels");
                });

            modelBuilder.Entity("HotelService.Models.HotelAmenity", b =>
                {
                    b.Property<int>("HotelAmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelAmenityId"));

                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.HasKey("HotelAmenityId");

                    b.HasIndex("AmenityId");

                    b.HasIndex("HotelId");

                    b.ToTable("MyHotelAmenities");
                });

            modelBuilder.Entity("HotelService.Models.HotelAmenity", b =>
                {
                    b.HasOne("HotelService.Models.Amenity", "Amenity")
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelService.Models.Hotel", "Hotel")
                        .WithMany("HotelAmenities")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelService.Models.Hotel", b =>
                {
                    b.Navigation("HotelAmenities");
                });
#pragma warning restore 612, 618
        }
    }
}
